
</div>

<div class=row">
<div id="footer" class="col-xs-12">
    <p>Web-application developed for UoS 2022 Hack Camp</p>
</div>
</div>
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->

<script src="js/bootstrap.min.js"></script>

<!--Bootstrap tables-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://unpkg.com/bootstrap-table@1.19.1/dist/bootstrap-table.min.js"></script>
<!-- heatmap -->
<script async
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAlZ8WDtnDLpwa4vOGvFAHww4kYAIJ1dTU&libraries=visualization&callback=initMap&v=weekly&channel=2"
</script>



</body>
</html>
