<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <!--Favicon-->
    <link rel="shortcut icon" href="Images/favicon.ico" type="image/x-icon">
    <!--Pie Chart  -->
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>


    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="/css/my-style.css" rel="stylesheet">
    <!--Bootstrap tables-->
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.19.1/dist/bootstrap-table.min.css">

    <title>Scottish Power - <?php echo $view->pageTitle; ?></title>
</head>

<body role="document">

<div class="container">
    <div  class="row">
        <div id="title" class="col-xs-12">
            <img class="scottishpower" src="Images/scottishpower.png" alt="Scottish Power logo" />
            <div class="pull-right"> <h2><?php echo $view->pageTitle ?> </h2></div>

        </div>
    </div>


    <div class="row">
        <div id="menu" class="col-xs-6 col-sm-3 col-md-2">
            <ul class="navbar-nav">
                <li><a href="index.php">Home</a></li>
                <li><a href="upload.php">Upload CSV</a></li>
                <li><a href="dataTable.php">Data Table</a></li>
                <li><a href="calculator.php">Mitigation Time Calc</a></li>
                <li><a href="piecharts.php">Risk Charts</a></li>
                <li><a href="exportcsv.php">Export Risks CSV</a></li>
                <li><a href="heatmap.php">Map</a></li>
            </ul>
        </div>

        <div id="content" class="col-xs-6 col-sm-9 col-md-10">
