<?php require('template/header.phtml') ?>

<div class="row page-header">
    <h1 class="page-title">Risk Mitigation Calculator</h1>
</div>
<div class="row">
    <div class="col-4">
        <form method="post">
            <div class="mb-3">
                <label for="district">District</label>
                <select class="form-select" name="district" value="All">
                    <option value="*" selected>All</option>
                    <option value="Dumfries">Dumfries</option>
                    <option value="Central & Fife">Central & Fife</option>
                    <option value="Glasgow">Glasgow</option>
                    <option value="Lanarkshire">Lanarkshire</option>
                    <option value="Edinburgh & Borders">Edinburgh & Borders</option>
                    <option value="Ayrshire & Clyde South">Ayrshire & Clyde South</option>
                </select>
            </div>
            <div class="mb-3">
                <select class="form-select" name="type" value="">
                    <option value="*" selected>All</option>
                    <option value="high">High</option>
                    <option value="medium">Medium</option>
                    <option value="low">Low</option>
                </select>
            </div>
            <div class="mb-3">
                <label for="resources" class="form-label">Resources</label>
                <input type="number" name="resources" placeholder="Resources" class="form-control" />
            </div>
            <button class="btn btn-primary" type="submit" name="submit">Calculate</button>
        </form>
    </div>
    <div class="col-2"></div>
    <div class="col-4">
        <form style="padding-top: 5rem;">
            <div class="input-group mb-3">
                <span class="input-group-text" id="basic-addon1">Time:</span>
                <input type="text" class="form-control" placeholder="Time" value="<?php if (isset($view->result)){echo $view->result;} ?>" disabled>
            </div>
        </form>
    </div>
    <div class="col-2"></div>
</div>
<!--<?php if (isset($view->result)) : ?>
    <p><?php echo $view->result; ?></p>
<?php endif; ?>-->

<?php require('template/footer.phtml') ?>
