<?php require('template/header.phtml') ?>

<div class="row page-header">
    <h1 class="page-title">Risk Mitigation Calculator</h1>
</div>
<div class="row">
    <div class="col-4">
        <form method="post" id="print">
            <div class="mb-3">
                <label for="district">District</label>
                <select class="form-select" name="district" value="<?php if (isset($_POST['submit'])) { echo $_POST['district']; } ?>">
                    <option value="*" <?php if (isset($_POST['submit'])){if ($_POST['district'] == '*') { echo 'selected'; }} ?>>All</option>
                    <option value="Dumfries" <?php if (isset($_POST['submit'])){if ($_POST['district'] == 'Dumfries') { echo 'selected'; }} ?>>Dumfries</option>
                    <option value="Central & Fife" <?php if (isset($_POST['submit'])){if ($_POST['district'] == 'Central & Fife') { echo 'selected'; }} ?>>Central & Fife</option>
                    <option value="Glasgow" <?php if (isset($_POST['submit'])){if ($_POST['district'] == 'Glasgow') { echo 'selected'; }} ?>>Glasgow</option>
                    <option value="Lanarkshire" <?php if (isset($_POST['submit'])){if ($_POST['district'] == 'Lanarkshire') { echo 'selected'; }} ?>>Lanarkshire</option>
                    <option value="Edinburgh & Borders" <?php if (isset($_POST['submit'])){if ($_POST['district'] == 'Edinburgh & Borders') { echo 'selected'; }} ?>>Edinburgh & Borders</option>
                    <option value="Ayrshire & Clyde South" <?php if (isset($_POST['submit'])){if ($_POST['district'] == 'Ayshire & Clyde South') { echo 'selected'; }} ?>>Ayrshire & Clyde South</option>
                </select>
            </div>
            <div class="mb-3">
                <label for="type">Risk Type</label>
                <select class="form-select" name="type" value="">
                    <option value="*" <?php if (isset($_POST['submit'])){if ($_POST['type'] == '*') { echo 'selected'; }} ?>>All</option>
                    <option value="high" <?php if (isset($_POST['submit'])){if ($_POST['type'] == 'high') { echo 'selected'; }} ?>>High</option>
                    <option value="medium" <?php if (isset($_POST['submit'])){if ($_POST['type'] == 'medium') { echo 'selected'; }} ?>>Medium</option>
                    <option value="low" <?php if (isset($_POST['submit'])){if ($_POST['type'] == 'low') { echo 'selected'; }} ?>>Low</option>
                </select>
            </div>
            <div class="mb-3">
                <label for="resources" class="form-label">Resources</label>
                <input type="number" name="resources" placeholder="Resources" class="form-control" <?php if (isset($_POST['submit'])) { echo 'value="' . $_POST['resources'] . '"'; } ?>/>
            </div>
            <button class="btn btn-primary" type="submit" name="submit">Calculate</button>
            <?php
            if (isset($_POST['submit'])) {
                echo '
                <button class="btn btn-primary" onClick="printPage()">Print</button>
                <script type="text/javascript">
                    function printPage(){
                        let printContents = document.getElementById("print").innerHTML;
                        let printContents2 = document.getElementById("print2").innerHTML;
                        let originalContents = document.body.innerHTML;

                        document.body.innerHTML = printContents + "<br/>" + printContents2;

                        window.print();

                        document.body.innerHTML = originalContents;
                    }
                </script>
                ';
            }
            ?>
        </form>
    </div>
    <div class="col-2"></div>
    <div class="col-4">
        <form style="padding-top: 5rem;" id="print2">
            <div class="input-group mb-3">
                <span class="input-group-text" id="basic-addon1">Time:</span>
                <input type="text" class="form-control" placeholder="Time" value="<?php if (isset($view->result)){echo $view->result;} ?>" disabled>
            </div>
        </form>
    </div>
    <div class="col-2"></div>
</div>

<?php require('template/footer.phtml') ?>
