<?php require('template/header.phtml') ?>

<div class="row page-header">
    <h1 style="text-align:center;">Risk Data Table</h1>
</div>
<div class="container">
    <table class="table" data-toggle="table" data-search="true" data-show-columns="true" data-pagination="true">
        <!--Table header with the column names in-->
        <thead>
        <tr>
            <th scope="col">Risk ID</th>
            <th scope="col">Lattitude</th>
            <th scope="col">Longitude</th>
            <th scope="col">Distance (m)</th>
            <th scope="col">District</th>
            <th scope="col">Risk Level</th>
        </tr>
        </thead>
        <tbody>
        <!--Creates a new table row for every record returned-->
        <?php foreach ($view->dataset as $dataset) {
            $riskColorClass = "";
            if ($dataset->getRiskLevel() == "High") {
                $riskColorClass = "table-danger";
            } else if ($dataset->getRiskLevel() == "Medium") {
                $riskColorClass = "table-warning";
            } else if ($dataset->getRiskLevel() == "Low") {
                $riskColorClass = "table-success";
            } else {
                $riskColorClass = "table-secondary";
            }
            echo '<tr>' .
                '<th scope="row">' . $dataset->getId() . '</th>' .
                '<td>' . $dataset->getLat() . '</td>' .
                '<td>' . $dataset->getLon() . '</td>' .
                '<td>' . $dataset->getDistance() . '</td>' .
                '<td>' . $dataset->getDistrict() . '</td>' .
                '<td class="' . $riskColorClass . '">' . $dataset->getRiskLevel() . '</td>' .
                '</tr>';
        }
        ?>
        </tbody>
    </table>
</div>

<?php require('template/footer.phtml') ?>
