<?php require("template/header.phtml") ?>

<div class="row page-header">
    <h1 class="page-title">Download Risks CSV</h1>
</div>

<form method="post">
    <div class="md-3">
        <label for="download" class="form-label">Click here to download a csv of all the current risks.</label>
    </div>
    <div class="md-3">
        <button type="submit" name="submit" class="btn btn-primary btn-lg">Download</button>
    </div>
</form>

<?php require("template/footer.phtml") ?>
