<?php require("template/header.phtml") ?>

<div class="row page-header">
    <h1 class="page-title">Download Risks CSV</h1>
</div>
<div class="row">
    <div class="col-3"></div>
    <div class="col-6 top-pad">
        <form method="post">
            <div class="col">
                <div class="row">
                    <label for="download" class="form-label form-text-centre label-lg">Click here to download a csv of all the current risks.</label>
                </div>
                <div class="row">
                    <button type="submit" name="submit" class="btn btn-primary btn-lg btn-block">Download</button>
                </div>
            </div>
        </form>
    </div>
    <div class="col-3"></div>
</div>

<?php require("template/footer.phtml") ?>
