<?php require('template/header.phtml') ?>

<div class="row page-header">
    <h1 class="page-title">Map</h1>
</div>

<div class="col-sm-12 col-md-12 col-lg-12 col-xl-12">
    <div class="row">

        <div class="col-sm-1 col-md-1 col-lg-1 col-xl-1">

        </div>

        <div class="col-sm-10 col-md-10 col-lg-10 col-xl-10" style="padding:2rem;">
            <div id="floating-panel" style="padding-bottom: 0.5rem;">
                <button onclick="toggleHeatMap()">Toggle Heatmap</button>
                <button onclick="changeGradient()">Change gradient</button>
                <button onclick="changeRadius()">Change radius</button>
                <button onclick="changeOpacity()">Change opacity</button>
            </div>
            <div id="map" style="height: 30rem;"></div>

        </div>

        <div class="col-sm-1 col-md-1 col-lg-1 col-xl-1">

        </div>
    </div>
</div>

<script type="text/javascript">
    let map, heatmap;


    function initMap() {
        const mapOptions = {
            zoom: 6,
            center: {lat: 56.073156, lng: -4.011995},
            mapTypeId: 'satellite'
        };

        map = new google.maps.Map(document.getElementById('map'), mapOptions);

        heatmap = new google.maps.visualization.HeatmapLayer({
            data: getPoints(),
            map: map,
        });
        heatmap.setMap(map);
    }


    function toggleHeatMap() {
        heatmap.setMap(heatmap.getMap() ? null : map);
    }

    function changeGradient() {
        var gradient = [
            'rgba(0, 255, 255, 0)',
            'rgba(0, 255, 255, 1)',
            'rgba(0, 191, 255, 1)',
            'rgba(0, 127, 255, 1)',
            'rgba(0, 63, 255, 1)',
            'rgba(0, 0, 255, 1)',
            'rgba(0, 0, 223, 1)',
            'rgba(0, 0, 191, 1)',
            'rgba(0, 0, 159, 1)',
            'rgba(0, 0, 127, 1)',
            'rgba(63, 0, 91, 1)',
            'rgba(127, 0, 63, 1)',
            'rgba(191, 0, 31, 1)',
            'rgba(255, 0, 0, 1)'
        ]

        heatmap.set('gradient', heatmap.get('gradient') ? null : gradient);
    }


    function changeRadius() {
        heatmap.set('radius', heatmap.get('radius') ? null : 20);
    }

    function changeOpacity() {
        heatmap.set('opacity', heatmap.get('opacity') ? null : 0.2);
    }

    function getPoints() {
        return [
            <?php
            foreach ($view->coordinates as $coordinate) {
                echo "new google.maps.LatLng(" . $coordinate[0] . "," . $coordinate[1] . "),";
            }
            ?>
        ];
    }
</script>


<?php require('template/footer.phtml') ?>
