<?php require('template/header.phtml') ?>

<div class="row page-header">
    <h1 class="page-title">Map</h1>
</div>

<div class="col-sm-12 col-md-12 col-lg-12 col-xl-12">
    <div class="row">

        <div class="col-sm-2 col-md-2 col-lg-2 col-xl-2">

        </div>

        <div class="col-sm-8 col-md-8 col-lg-8 col-xl-8" style="padding:2rem;">
            <div id="floating-panel" style="padding-bottom: 0.5rem;">
                <button onclick="toggleHeatMap()">Toggle Heatmap</button>
                <button onclick="changeGradient()">Change gradient</button>
                <button onclick="changeRadius()">Change radius</button>
                <button onclick="changeOpacity()">Change opacity</button>
            </div>
            <div id="map" style="height: 30rem;"></div>

        </div>

        <div class="col-sm-2 col-md-2 col-lg-2 col-xl-2">

        </div>
    </div>
</div>

<script src="js/map.js" type="text/javascript"></script>


<?php require('template/footer.phtml') ?>
