<?php require('template/header.phtml') ?>

<div class="row page-header">
    <h1 class="page-title">Risk Charts</h1>
</div>
<div class="col-sm-12 col-md-12 col-lg-12 col-xl-12">
    <div class="row">
<!-- TODO modify the pie chart code to be in a forloop,
      the for loop iterates through an array of district
      names and calls a function to determine percentages-->
        <!--Pie Chart  -->
        <script type="text/javascript">
            google.charts.load('current', {'packages':['corechart']});
            google.charts.setOnLoadCallback(drawChart);

            function drawChart() {
                //Define Chart
                var data = google.visualization.arrayToDataTable([
                    ['Risks', 'Percentage'],
                    ['High Risk', <?php echo $view->highRisk ;?>],
                    ['Medium Risk', <?php echo $view->medRisk ;?>],
                    ['Low Risk', <?php echo $view->lowRisk ;?>]
                ]);

                var options = {
                    title: 'Global Risks',
                    colors: ['red','orange','yellow'],
                    pieSliceTextStyle: {
                        color: 'black'
                    }
                };

                //Instantiate and draw Chart
                var chart = new google.visualization.PieChart(document.getElementById('globalChart'));
                chart.draw(data, options);
            }
        </script>
        <div id="globalChart" style="width: 900px; height: 500px;">

        </div>
    </div>

    <div class='row'>
        <?php
        //Output buffer used for efficiency with a lot of echos
        ob_start();
        foreach($view->districts as $district) {
            //use method in Chart to find the risk percentage values of the current district
            //Then update values for each chart to be called in javascript below
            $values = $view->chart->calculateChart($district);
            //echo "[DISTRICT:".$district."]";
            $view->highRisk = intval($values[0]);
            //echo "[HIGH RISK: ".$view->highRisk."]";
            $view->medRisk = intval($values[1]);
            //echo "[MED RISK: ".$view->medRisk."]";
            $view->lowRisk = intval($values[2]);
            //echo "[LOW RISK: ".$view->lowRisk."]";
            //Creates a pie chart for each district - here is the issue, the pie charts won't appear
            echo "<div class ='col-sm-6 col-md-6 col-lg-6 col-xl-6' style='border:solid green;'>";
            echo    "<div id='".$district."Chart'>";
            echo        "<script type='text/javascript'>";
            echo            "google.charts.load('current', {'packages':['corechart']});";
            echo            "google.charts.setOnLoadCallback(drawChart);";

            echo            "function drawChart() {";
            //Define Chart
            echo                "var data = google.visualization.arrayToDataTable([";
            echo                    "['Risks', 'Percentage'],";
            echo                    "['High Risk',".$view->highRisk."],";
            echo                    "['Medium Risk',".$view->medRisk."],";
            echo                    "['Low Risk',".$view->lowRisk."]";
            echo                "]);";

            echo                "var options = {";
            echo                    "title: '".$district." Risks',";
            echo                    "colors: ['red','orange','yellow'],";
            echo                    "pieSliceTextStyle: {";
            echo                    "color: 'black'";
            echo                "}";
            echo            "};";

            //Instantiate and draw Chart, the $district variable is used as a parameter in a query to count
            //the risks in the database for that district
            echo            "var chart = new google.visualization.PieChart(document.getElementById('".strval($district)."Chart'));";
            echo            "chart.draw(data, options);";
            echo            "}";
            echo        "</script>";
            echo    "</div>";
            echo "</div>";
        }
        ob_end_flush();
        ?>
    </div>
</div>




<?php require('template/footer.phtml') ?>
