<?php require('template/header.phtml') ?>


<div></div>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
        google.charts.load('current', {'packages':['corechart']});
        google.charts.setOnLoadCallback(drawChart);

        function drawChart() {

            var data = google.visualization.arrayToDataTable([
                ['district', 'distance']
                <?php
                $database = new Database();
                $statement = $database->connect()->prepare("SELECT * FROM Risks");
                $statement->execute();
                while ($result = $statement->fetch()) {
                    echo"['".$result['district']."','".$result['distance']."']";
                }
                ?>
            ]);

            var options = {
                title: 'My Daily Activities'
            };

            var chart = new google.visualization.PieChart(document.getElementById('piechart'));

            chart.draw(data, options);
        }
    </script>
</div>
<body>
<div id="piechart" style="width: 900px; height: 500px;"></div>
</body>



<?php require('template/footer.phtml') ?>
