<?php require('template/header.phtml') ?>

<div class="row page-header">
    <h1 style="text-align:center;">Calculate Time</h1>
</div>
<div class="container">
    <form method="post" action="maintenancecalc.php">
        <div class="mb-3">
            <label for="resources">Resources</label>
            <input name="resources" type="number" class="form-control">
        </div>
        <div class="mb-3">
            <label for="risks">Risks</label>
            <input name="risks" type="number" class="form-control">
        </div>
        <button type="submit" name="calculate" class="btn btn-primary">Calculate</button>
    </form>
    <?php
    if (isset($_POST['calculate'])) {
        echo '
        <div class="top-pad">
            <form>
                <div class="input-group mb-3">
                    <span class="input-group-text" id="basic-addon3">Time required: </span>
                    <input type="text" class="form-control" value="' . $view->maintenanceResult . ' days' . '" disabled>
                </div>
            </form>
        </div>
        ';
    }
    ?>
</div>

<?php require('template/footer.phtml') ?>
