<?php require('template/header.phtml') ?>

<div class="row page-header">
    <h1 class="page-title">Risk Charts</h1>
</div>
<div class="col-sm-12 col-md-12 col-lg-12 col-xl-12" id="print">
    <div class="row">
        <div class="col-sm-2 col-md-2 col-lg-2 col-xl-2">

        </div>
<!-- TODO modify the pie chart code to be in a forloop,
      the for loop iterates through an array of district
      names and calls a function to determine percentages-->
        <!--Pie Chart  -->
        <script type="text/javascript">
            google.charts.load('current', {'packages':['corechart']});
            google.charts.setOnLoadCallback(drawChart);

            function drawChart() {
                //Define Chart
                var data = google.visualization.arrayToDataTable([
                    ['Risks', 'Percentage'],
                    ['High Risk', <?php echo intval($view->highRisk);?>],
                    ['Medium Risk', <?php echo intval($view->medRisk);?>],
                    ['Low Risk', <?php echo intval($view->lowRisk);?>]
                ]);

                var options = {
                    title: 'Global Risks',
                    colors: ['red','orange','yellow'],
                    pieSliceTextStyle: {
                        color: 'black'
                    }
                };

                //Instantiate and draw Chart
                var chart = new google.visualization.PieChart(document.getElementById('globalChart'));
                chart.draw(data, options);
            }
        </script>
        <div class="col-sm-8 col-md-8 col-lg-8 col-xl-8">
            <div id="globalChart" style="width: 900px; height: 500px;">

            </div>
        </div>

        <div class="col-sm-2 col-md-2 col-lg-2 col-xl-2">

        </div>
    </div>

    <div class='row'>
        <?php
        //Output buffer used for efficiency with a lot of echos
        ob_start();
        foreach($view->risks as $risk) {
            //Creates a pie chart for the current district
            echo "<div class ='col-sm-4 col-md-4 col-lg-4 col-xl-4'>";
            echo    "<div id='".$risk."Chart'>";
            echo        "<script type='text/javascript'>";
            echo            "google.charts.load('current', {'packages':['corechart']});";
            echo            "google.charts.setOnLoadCallback(drawChart);";

            echo            "function drawChart() {";
            //Define Chart
            echo                "var data = google.visualization.arrayToDataTable([";
            echo                    "['District', 'Count'],";
                                    foreach($view->districts as $district) {
                                        if($risk=='high') {
                                            echo "['".$district->getName()."',".$district->getHigh()."]";
                                        } else if($risk=='med') {
                                            echo "['".$district->getName()."',".$district->getMed()."]";
                                        } else {
                                            echo "['".$district->getName()."',".$district->getLow()."]";
                                        }
                                        if ($district->getName() != 'Ayrshire & Clyde South') {
                                            echo ",";
                                        }
                                    }
            echo                "]);";

            echo                "var options = {";
            echo                    "title: '"; switch ($risk) {case "high": echo "High"; break; case "med": echo "Medium"; break; case "low":echo "Low"; break; } echo " Risks',";
            echo                    "colors: ['purple','orange','blue','yellow','red','green'],";
            echo                    "pieSliceTextStyle: {";
            echo                    "color: 'black'";
            echo                "}";
            echo            "};";

            //Instantiate and draw Chart, the $district variable is used as a parameter in a query to count
            //the risks in the database for that district
            echo            "var chart = new google.visualization.PieChart(document.getElementById('".$risk."Chart'));";
            echo            "chart.draw(data, options);";
            echo            "}";
            echo        "</script>";
            echo    "</div>";
            echo "</div>";
        }
        ob_end_flush();
        ?>
    </div>


    <div class='row'>
        <?php
        //Output buffer used for efficiency with a lot of echos
        ob_start();
        foreach($view->districts as $district) {
            //Creates a pie chart for the current district
            echo "<div class ='col-sm-6 col-md-6 col-lg-6 col-xl-6'>";
            echo    "<div id='".$district->getName()."Chart'>";
            echo        "<script type='text/javascript'>";
            echo            "google.charts.load('current', {'packages':['corechart']});";
            echo            "google.charts.setOnLoadCallback(drawChart);";

            echo            "function drawChart() {";
            //Define Chart
            echo                "var data = google.visualization.arrayToDataTable([";
            echo                    "['Risks', 'Percentage'],";
            echo                    "['High Risk',".$district->getHigh()."],";
            echo                    "['Medium Risk',".$district->getMed()."],";
            echo                    "['Low Risk',".$district->getLow()."]";
            echo                "]);";

            echo                "var options = {";
            echo                    "title: '".$district->getName()." Risks',";
            echo                    "colors: ['red','orange','yellow'],";
            echo                    "pieSliceTextStyle: {";
            echo                    "color: 'black'";
            echo                "}";
            echo            "};";

            //Instantiate and draw Chart, the $district variable is used as a parameter in a query to count
            //the risks in the database for that district
            echo            "var chart = new google.visualization.PieChart(document.getElementById('".strval($district->getName())."Chart'));";
            echo            "chart.draw(data, options);";
            echo            "}";
            echo        "</script>";
            echo    "</div>";
            echo "</div>";
        }
        ob_end_flush();
        ?>
    </div>
</div>
<div class="row form-container">
    <button class="btn btn-primary" onClick="printPage()">Download</button>
    <script type="text/javascript">
        function printPage(){
            let printContents = document.getElementById("print").innerHTML;
            let originalContents = document.body.innerHTML;

            document.body.innerHTML = printContents;

            window.print();

            document.body.innerHTML = originalContents;
        }
    </script>
</div>


<?php require('template/footer.phtml') ?>
