<?php require('template/header.phtml') ?>

<div class="row page-header">
    <h1 class="page-title">Risk Charts</h1>
</div>
<div class="col-sm-12 col-md-12 col-lg-12 col-xl-12">
    <div class="row">
        <div class="col-sm-2 col-md-2 col-lg-2 col-xl-2">

        </div>
<!-- TODO modify the pie chart code to be in a forloop,
      the for loop iterates through an array of district
      names and calls a function to determine percentages-->
        <!--Pie Chart  -->
        <script type="text/javascript">
            google.charts.load('current', {'packages':['corechart']});
            google.charts.setOnLoadCallback(drawChart);

            function drawChart() {
                //Define Chart
                var data = google.visualization.arrayToDataTable([
                    ['Risks', 'Percentage'],
                    ['High Risk', <?php echo intval($view->highRisk);?>],
                    ['Medium Risk', <?php echo intval($view->medRisk);?>],
                    ['Low Risk', <?php echo intval($view->lowRisk);?>]
                ]);

                var options = {
                    title: 'Global Risks',
                    colors: ['red','orange','yellow'],
                    pieSliceTextStyle: {
                        color: 'black'
                    }
                };

                //Instantiate and draw Chart
                var chart = new google.visualization.PieChart(document.getElementById('globalChart'));
                chart.draw(data, options);
            }
        </script>
        <div class="col-sm-8 col-md-8 col-lg-8 col-xl-8">
            <div id="globalChart" style="width: 900px; height: 500px;">

            </div>
        </div>

        <div class="col-sm-2 col-md-2 col-lg-2 col-xl-2">

        </div>
    </div>
</div>
<?php require('template/footer.phtml') ?>
