<?php require('template/header.phtml') ?>

<div>
    <div class="row page-header">
        <h1 class="page-title">Upload Data</h1>
    </div>
    <div class="form-container">
        <form action="../upload.php" method="post" enctype="multipart/form-data">
            <div class="mb-3">
                <label for="chosenFile" class="form-label">Risk file (csv)</label>
                <input type="file" class="form-control" accept="text/csv">
                <div class="form-text">Only .csv files accepted</div>
            </div>
            <button type="submit" name="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>

<?php require('template/footer.phtml') ?>
