# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  schedule:
    - cron: '30 9,4 * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deploy2
      uses: trendyminds/github-actions-rsync@master
      with:
        RSYNC_OPTIONS: -avzr --delete --exclude '.git*'
        RSYNC_TARGET: ${{ secrets.DEPLOY_PATH }}
        RSYNC_SOURCE: src/
      env:
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
        SSH_USERNAME: ${{ secrets.DEPLOY_USER }}
        SSH_HOSTNAME: ${{ secrets.DEPLOY_USER }}