# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  schedule:
    - cron: '30 9,4 * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: install ssh pass
        run: apt-get install sshpass
      - name: rsync with sshpass
        run: sshpass -p ${{ secrets.DEPLOY_PASS }} rsync -avz /src/ ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:public_html/